/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BillingManifestItem type.
 */
public class BillingManifestItem {
    private String transactionType;
    private String kind;
    private Integer amountInCents;
    private String memo;
    private Integer discountAmountInCents;
    private Integer taxableAmountInCents;
    private Integer componentId;

    /**
     * Default constructor.
     */
    public BillingManifestItem() {
    }

    /**
     * Initialization constructor.
     * @param  transactionType  String value for transactionType.
     * @param  kind  String value for kind.
     * @param  amountInCents  Integer value for amountInCents.
     * @param  memo  String value for memo.
     * @param  discountAmountInCents  Integer value for discountAmountInCents.
     * @param  taxableAmountInCents  Integer value for taxableAmountInCents.
     * @param  componentId  Integer value for componentId.
     */
    public BillingManifestItem(
            String transactionType,
            String kind,
            Integer amountInCents,
            String memo,
            Integer discountAmountInCents,
            Integer taxableAmountInCents,
            Integer componentId) {
        this.transactionType = transactionType;
        this.kind = kind;
        this.amountInCents = amountInCents;
        this.memo = memo;
        this.discountAmountInCents = discountAmountInCents;
        this.taxableAmountInCents = taxableAmountInCents;
        this.componentId = componentId;
    }

    /**
     * Getter for TransactionType.
     * @return Returns the String
     */
    @JsonGetter("transaction_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Setter for TransactionType.
     * @param transactionType Value for String
     */
    @JsonSetter("transaction_type")
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * Getter for Kind.
     * @return Returns the String
     */
    @JsonGetter("kind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getKind() {
        return kind;
    }

    /**
     * Setter for Kind.
     * @param kind Value for String
     */
    @JsonSetter("kind")
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * Getter for AmountInCents.
     * @return Returns the Integer
     */
    @JsonGetter("amount_in_cents")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAmountInCents() {
        return amountInCents;
    }

    /**
     * Setter for AmountInCents.
     * @param amountInCents Value for Integer
     */
    @JsonSetter("amount_in_cents")
    public void setAmountInCents(Integer amountInCents) {
        this.amountInCents = amountInCents;
    }

    /**
     * Getter for Memo.
     * @return Returns the String
     */
    @JsonGetter("memo")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMemo() {
        return memo;
    }

    /**
     * Setter for Memo.
     * @param memo Value for String
     */
    @JsonSetter("memo")
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * Getter for DiscountAmountInCents.
     * @return Returns the Integer
     */
    @JsonGetter("discount_amount_in_cents")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDiscountAmountInCents() {
        return discountAmountInCents;
    }

    /**
     * Setter for DiscountAmountInCents.
     * @param discountAmountInCents Value for Integer
     */
    @JsonSetter("discount_amount_in_cents")
    public void setDiscountAmountInCents(Integer discountAmountInCents) {
        this.discountAmountInCents = discountAmountInCents;
    }

    /**
     * Getter for TaxableAmountInCents.
     * @return Returns the Integer
     */
    @JsonGetter("taxable_amount_in_cents")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTaxableAmountInCents() {
        return taxableAmountInCents;
    }

    /**
     * Setter for TaxableAmountInCents.
     * @param taxableAmountInCents Value for Integer
     */
    @JsonSetter("taxable_amount_in_cents")
    public void setTaxableAmountInCents(Integer taxableAmountInCents) {
        this.taxableAmountInCents = taxableAmountInCents;
    }

    /**
     * Getter for ComponentId.
     * @return Returns the Integer
     */
    @JsonGetter("component_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getComponentId() {
        return componentId;
    }

    /**
     * Setter for ComponentId.
     * @param componentId Value for Integer
     */
    @JsonSetter("component_id")
    public void setComponentId(Integer componentId) {
        this.componentId = componentId;
    }

    /**
     * Converts this BillingManifestItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BillingManifestItem [" + "transactionType=" + transactionType + ", kind=" + kind
                + ", amountInCents=" + amountInCents + ", memo=" + memo + ", discountAmountInCents="
                + discountAmountInCents + ", taxableAmountInCents=" + taxableAmountInCents
                + ", componentId=" + componentId + "]";
    }

    /**
     * Builds a new {@link BillingManifestItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BillingManifestItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .transactionType(getTransactionType())
                .kind(getKind())
                .amountInCents(getAmountInCents())
                .memo(getMemo())
                .discountAmountInCents(getDiscountAmountInCents())
                .taxableAmountInCents(getTaxableAmountInCents())
                .componentId(getComponentId());
        return builder;
    }

    /**
     * Class to build instances of {@link BillingManifestItem}.
     */
    public static class Builder {
        private String transactionType;
        private String kind;
        private Integer amountInCents;
        private String memo;
        private Integer discountAmountInCents;
        private Integer taxableAmountInCents;
        private Integer componentId;



        /**
         * Setter for transactionType.
         * @param  transactionType  String value for transactionType.
         * @return Builder
         */
        public Builder transactionType(String transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        /**
         * Setter for kind.
         * @param  kind  String value for kind.
         * @return Builder
         */
        public Builder kind(String kind) {
            this.kind = kind;
            return this;
        }

        /**
         * Setter for amountInCents.
         * @param  amountInCents  Integer value for amountInCents.
         * @return Builder
         */
        public Builder amountInCents(Integer amountInCents) {
            this.amountInCents = amountInCents;
            return this;
        }

        /**
         * Setter for memo.
         * @param  memo  String value for memo.
         * @return Builder
         */
        public Builder memo(String memo) {
            this.memo = memo;
            return this;
        }

        /**
         * Setter for discountAmountInCents.
         * @param  discountAmountInCents  Integer value for discountAmountInCents.
         * @return Builder
         */
        public Builder discountAmountInCents(Integer discountAmountInCents) {
            this.discountAmountInCents = discountAmountInCents;
            return this;
        }

        /**
         * Setter for taxableAmountInCents.
         * @param  taxableAmountInCents  Integer value for taxableAmountInCents.
         * @return Builder
         */
        public Builder taxableAmountInCents(Integer taxableAmountInCents) {
            this.taxableAmountInCents = taxableAmountInCents;
            return this;
        }

        /**
         * Setter for componentId.
         * @param  componentId  Integer value for componentId.
         * @return Builder
         */
        public Builder componentId(Integer componentId) {
            this.componentId = componentId;
            return this;
        }

        /**
         * Builds a new {@link BillingManifestItem} object using the set fields.
         * @return {@link BillingManifestItem}
         */
        public BillingManifestItem build() {
            return new BillingManifestItem(transactionType, kind, amountInCents, memo,
                    discountAmountInCents, taxableAmountInCents, componentId);
        }
    }
}
