/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for ComponentPricePointPrice type.
 */
public class ComponentPricePointPrice {
    private Integer id;
    private Integer componentId;
    private Integer startingQuantity;
    private OptionalNullable<Integer> endingQuantity;
    private String unitPrice;

    /**
     * Default constructor.
     */
    public ComponentPricePointPrice() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  componentId  Integer value for componentId.
     * @param  startingQuantity  Integer value for startingQuantity.
     * @param  endingQuantity  Integer value for endingQuantity.
     * @param  unitPrice  String value for unitPrice.
     */
    public ComponentPricePointPrice(
            Integer id,
            Integer componentId,
            Integer startingQuantity,
            Integer endingQuantity,
            String unitPrice) {
        this.id = id;
        this.componentId = componentId;
        this.startingQuantity = startingQuantity;
        this.endingQuantity = OptionalNullable.of(endingQuantity);
        this.unitPrice = unitPrice;
    }

    /**
     * Internal initialization constructor.
     */
    protected ComponentPricePointPrice(Integer id, Integer componentId, Integer startingQuantity,
            OptionalNullable<Integer> endingQuantity, String unitPrice) {
        this.id = id;
        this.componentId = componentId;
        this.startingQuantity = startingQuantity;
        this.endingQuantity = endingQuantity;
        this.unitPrice = unitPrice;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for ComponentId.
     * @return Returns the Integer
     */
    @JsonGetter("component_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getComponentId() {
        return componentId;
    }

    /**
     * Setter for ComponentId.
     * @param componentId Value for Integer
     */
    @JsonSetter("component_id")
    public void setComponentId(Integer componentId) {
        this.componentId = componentId;
    }

    /**
     * Getter for StartingQuantity.
     * @return Returns the Integer
     */
    @JsonGetter("starting_quantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getStartingQuantity() {
        return startingQuantity;
    }

    /**
     * Setter for StartingQuantity.
     * @param startingQuantity Value for Integer
     */
    @JsonSetter("starting_quantity")
    public void setStartingQuantity(Integer startingQuantity) {
        this.startingQuantity = startingQuantity;
    }

    /**
     * Internal Getter for EndingQuantity.
     * @return Returns the Internal Integer
     */
    @JsonGetter("ending_quantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetEndingQuantity() {
        return this.endingQuantity;
    }

    /**
     * Getter for EndingQuantity.
     * @return Returns the Integer
     */
    public Integer getEndingQuantity() {
        return OptionalNullable.getFrom(endingQuantity);
    }

    /**
     * Setter for EndingQuantity.
     * @param endingQuantity Value for Integer
     */
    @JsonSetter("ending_quantity")
    public void setEndingQuantity(Integer endingQuantity) {
        this.endingQuantity = OptionalNullable.of(endingQuantity);
    }

    /**
     * UnSetter for EndingQuantity.
     */
    public void unsetEndingQuantity() {
        endingQuantity = null;
    }

    /**
     * Getter for UnitPrice.
     * @return Returns the String
     */
    @JsonGetter("unit_price")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Setter for UnitPrice.
     * @param unitPrice Value for String
     */
    @JsonSetter("unit_price")
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * Converts this ComponentPricePointPrice into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ComponentPricePointPrice [" + "id=" + id + ", componentId=" + componentId
                + ", startingQuantity=" + startingQuantity + ", endingQuantity=" + endingQuantity
                + ", unitPrice=" + unitPrice + "]";
    }

    /**
     * Builds a new {@link ComponentPricePointPrice.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ComponentPricePointPrice.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .componentId(getComponentId())
                .startingQuantity(getStartingQuantity())
                .unitPrice(getUnitPrice());
        builder.endingQuantity = internalGetEndingQuantity();
        return builder;
    }

    /**
     * Class to build instances of {@link ComponentPricePointPrice}.
     */
    public static class Builder {
        private Integer id;
        private Integer componentId;
        private Integer startingQuantity;
        private OptionalNullable<Integer> endingQuantity;
        private String unitPrice;



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for componentId.
         * @param  componentId  Integer value for componentId.
         * @return Builder
         */
        public Builder componentId(Integer componentId) {
            this.componentId = componentId;
            return this;
        }

        /**
         * Setter for startingQuantity.
         * @param  startingQuantity  Integer value for startingQuantity.
         * @return Builder
         */
        public Builder startingQuantity(Integer startingQuantity) {
            this.startingQuantity = startingQuantity;
            return this;
        }

        /**
         * Setter for endingQuantity.
         * @param  endingQuantity  Integer value for endingQuantity.
         * @return Builder
         */
        public Builder endingQuantity(Integer endingQuantity) {
            this.endingQuantity = OptionalNullable.of(endingQuantity);
            return this;
        }

        /**
         * UnSetter for endingQuantity.
         * @return Builder
         */
        public Builder unsetEndingQuantity() {
            endingQuantity = null;
            return this;
        }

        /**
         * Setter for unitPrice.
         * @param  unitPrice  String value for unitPrice.
         * @return Builder
         */
        public Builder unitPrice(String unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        /**
         * Builds a new {@link ComponentPricePointPrice} object using the set fields.
         * @return {@link ComponentPricePointPrice}
         */
        public ComponentPricePointPrice build() {
            return new ComponentPricePointPrice(id, componentId, startingQuantity, endingQuantity,
                    unitPrice);
        }
    }
}
