/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * CurrentVaultEnum to be used.
 */
public enum CurrentVaultEnum {
    AUTHORIZENET,

    TRUST_COMMERCE,

    PAYMENT_EXPRESS,

    BEANSTREAM,

    BRAINTREE_BLUE,

    PAYPAL,

    EWAY,

    EWAY_RAPID_STD,

    STRIPE_CONNECT,

    PIN,

    WIRECARD,

    BPOINT,

    FIRSTDATA,

    ELAVON,

    CYBERSOURCE,

    PAYMILL,

    MONERIS,

    LITLE,

    SQUARE;


    private static TreeMap<String, CurrentVaultEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        AUTHORIZENET.value = "authorizenet";
        TRUST_COMMERCE.value = "trust_commerce";
        PAYMENT_EXPRESS.value = "payment_express";
        BEANSTREAM.value = "beanstream";
        BRAINTREE_BLUE.value = "braintree_blue";
        PAYPAL.value = "paypal";
        EWAY.value = "eway";
        EWAY_RAPID_STD.value = "eway_rapid_std";
        STRIPE_CONNECT.value = "stripe_connect";
        PIN.value = "pin";
        WIRECARD.value = "wirecard";
        BPOINT.value = "bpoint";
        FIRSTDATA.value = "firstdata";
        ELAVON.value = "elavon";
        CYBERSOURCE.value = "cybersource";
        PAYMILL.value = "paymill";
        MONERIS.value = "moneris";
        LITLE.value = "litle";
        SQUARE.value = "square";

        valueMap.put("authorizenet", AUTHORIZENET);
        valueMap.put("trust_commerce", TRUST_COMMERCE);
        valueMap.put("payment_express", PAYMENT_EXPRESS);
        valueMap.put("beanstream", BEANSTREAM);
        valueMap.put("braintree_blue", BRAINTREE_BLUE);
        valueMap.put("paypal", PAYPAL);
        valueMap.put("eway", EWAY);
        valueMap.put("eway_rapid_std", EWAY_RAPID_STD);
        valueMap.put("stripe_connect", STRIPE_CONNECT);
        valueMap.put("pin", PIN);
        valueMap.put("wirecard", WIRECARD);
        valueMap.put("bpoint", BPOINT);
        valueMap.put("firstdata", FIRSTDATA);
        valueMap.put("elavon", ELAVON);
        valueMap.put("cybersource", CYBERSOURCE);
        valueMap.put("paymill", PAYMILL);
        valueMap.put("moneris", MONERIS);
        valueMap.put("litle", LITLE);
        valueMap.put("square", SQUARE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static CurrentVaultEnum constructFromString(String toConvert) throws IOException {
        CurrentVaultEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static CurrentVaultEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CurrentVaultEnum values to list of string values.
     * @param toConvert The list of CurrentVaultEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<CurrentVaultEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (CurrentVaultEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 