/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Errors2 type.
 */
public class Errors2 {
    private Double componentId;
    private Double pricePoint;
    private String message;

    /**
     * Default constructor.
     */
    public Errors2() {
    }

    /**
     * Initialization constructor.
     * @param  componentId  Double value for componentId.
     * @param  pricePoint  Double value for pricePoint.
     * @param  message  String value for message.
     */
    public Errors2(
            Double componentId,
            Double pricePoint,
            String message) {
        this.componentId = componentId;
        this.pricePoint = pricePoint;
        this.message = message;
    }

    /**
     * Getter for ComponentId.
     * @return Returns the Double
     */
    @JsonGetter("component_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getComponentId() {
        return componentId;
    }

    /**
     * Setter for ComponentId.
     * @param componentId Value for Double
     */
    @JsonSetter("component_id")
    public void setComponentId(Double componentId) {
        this.componentId = componentId;
    }

    /**
     * Getter for PricePoint.
     * @return Returns the Double
     */
    @JsonGetter("price_point")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPricePoint() {
        return pricePoint;
    }

    /**
     * Setter for PricePoint.
     * @param pricePoint Value for Double
     */
    @JsonSetter("price_point")
    public void setPricePoint(Double pricePoint) {
        this.pricePoint = pricePoint;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Converts this Errors2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors2 [" + "componentId=" + componentId + ", pricePoint=" + pricePoint
                + ", message=" + message + "]";
    }

    /**
     * Builds a new {@link Errors2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .componentId(getComponentId())
                .pricePoint(getPricePoint())
                .message(getMessage());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors2}.
     */
    public static class Builder {
        private Double componentId;
        private Double pricePoint;
        private String message;



        /**
         * Setter for componentId.
         * @param  componentId  Double value for componentId.
         * @return Builder
         */
        public Builder componentId(Double componentId) {
            this.componentId = componentId;
            return this;
        }

        /**
         * Setter for pricePoint.
         * @param  pricePoint  Double value for pricePoint.
         * @return Builder
         */
        public Builder pricePoint(Double pricePoint) {
            this.pricePoint = pricePoint;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Builds a new {@link Errors2} object using the set fields.
         * @return {@link Errors2}
         */
        public Errors2 build() {
            return new Errors2(componentId, pricePoint, message);
        }
    }
}
