/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Errors11 type.
 */
public class Errors11 {
    private List<String> pricingScheme;
    private List<String> prices;

    /**
     * Default constructor.
     */
    public Errors11() {
    }

    /**
     * Initialization constructor.
     * @param  pricingScheme  List of String value for pricingScheme.
     * @param  prices  List of String value for prices.
     */
    public Errors11(
            List<String> pricingScheme,
            List<String> prices) {
        this.pricingScheme = pricingScheme;
        this.prices = prices;
    }

    /**
     * Getter for PricingScheme.
     * @return Returns the List of String
     */
    @JsonGetter("pricing_scheme")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPricingScheme() {
        return pricingScheme;
    }

    /**
     * Setter for PricingScheme.
     * @param pricingScheme Value for List of String
     */
    @JsonSetter("pricing_scheme")
    public void setPricingScheme(List<String> pricingScheme) {
        this.pricingScheme = pricingScheme;
    }

    /**
     * Getter for Prices.
     * @return Returns the List of String
     */
    @JsonGetter("prices")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPrices() {
        return prices;
    }

    /**
     * Setter for Prices.
     * @param prices Value for List of String
     */
    @JsonSetter("prices")
    public void setPrices(List<String> prices) {
        this.prices = prices;
    }

    /**
     * Converts this Errors11 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors11 [" + "pricingScheme=" + pricingScheme + ", prices=" + prices + "]";
    }

    /**
     * Builds a new {@link Errors11.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors11.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pricingScheme(getPricingScheme())
                .prices(getPrices());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors11}.
     */
    public static class Builder {
        private List<String> pricingScheme;
        private List<String> prices;



        /**
         * Setter for pricingScheme.
         * @param  pricingScheme  List of String value for pricingScheme.
         * @return Builder
         */
        public Builder pricingScheme(List<String> pricingScheme) {
            this.pricingScheme = pricingScheme;
            return this;
        }

        /**
         * Setter for prices.
         * @param  prices  List of String value for prices.
         * @return Builder
         */
        public Builder prices(List<String> prices) {
            this.prices = prices;
            return this;
        }

        /**
         * Builds a new {@link Errors11} object using the set fields.
         * @return {@link Errors11}
         */
        public Errors11 build() {
            return new Errors11(pricingScheme, prices);
        }
    }
}
