/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Errors18 type.
 */
public class Errors18 {
    private Subscription1 subscription;

    /**
     * Default constructor.
     */
    public Errors18() {
    }

    /**
     * Initialization constructor.
     * @param  subscription  Subscription1 value for subscription.
     */
    public Errors18(
            Subscription1 subscription) {
        this.subscription = subscription;
    }

    /**
     * Getter for Subscription.
     * @return Returns the Subscription1
     */
    @JsonGetter("subscription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Subscription1 getSubscription() {
        return subscription;
    }

    /**
     * Setter for Subscription.
     * @param subscription Value for Subscription1
     */
    @JsonSetter("subscription")
    public void setSubscription(Subscription1 subscription) {
        this.subscription = subscription;
    }

    /**
     * Converts this Errors18 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors18 [" + "subscription=" + subscription + "]";
    }

    /**
     * Builds a new {@link Errors18.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors18.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .subscription(getSubscription());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors18}.
     */
    public static class Builder {
        private Subscription1 subscription;



        /**
         * Setter for subscription.
         * @param  subscription  Subscription1 value for subscription.
         * @return Builder
         */
        public Builder subscription(Subscription1 subscription) {
            this.subscription = subscription;
            return this;
        }

        /**
         * Builds a new {@link Errors18} object using the set fields.
         * @return {@link Errors18}
         */
        public Errors18 build() {
            return new Errors18(subscription);
        }
    }
}
