/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Errors15 type.
 */
public class Errors15 {
    private Refund1 refund;

    /**
     * Default constructor.
     */
    public Errors15() {
    }

    /**
     * Initialization constructor.
     * @param  refund  Refund1 value for refund.
     */
    public Errors15(
            Refund1 refund) {
        this.refund = refund;
    }

    /**
     * Getter for Refund.
     * @return Returns the Refund1
     */
    @JsonGetter("refund")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Refund1 getRefund() {
        return refund;
    }

    /**
     * Setter for Refund.
     * @param refund Value for Refund1
     */
    @JsonSetter("refund")
    public void setRefund(Refund1 refund) {
        this.refund = refund;
    }

    /**
     * Converts this Errors15 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors15 [" + "refund=" + refund + "]";
    }

    /**
     * Builds a new {@link Errors15.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors15.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .refund(getRefund());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors15}.
     */
    public static class Builder {
        private Refund1 refund;



        /**
         * Setter for refund.
         * @param  refund  Refund1 value for refund.
         * @return Builder
         */
        public Builder refund(Refund1 refund) {
            this.refund = refund;
            return this;
        }

        /**
         * Builds a new {@link Errors15} object using the set fields.
         * @return {@link Errors15}
         */
        public Errors15 build() {
            return new Errors15(refund);
        }
    }
}
