/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Errors1 type.
 */
public class Errors1 {
    private List<String> base;

    /**
     * Default constructor.
     */
    public Errors1() {
    }

    /**
     * Initialization constructor.
     * @param  base  List of String value for base.
     */
    public Errors1(
            List<String> base) {
        this.base = base;
    }

    /**
     * Getter for Base.
     * @return Returns the List of String
     */
    @JsonGetter("base")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getBase() {
        return base;
    }

    /**
     * Setter for Base.
     * @param base Value for List of String
     */
    @JsonSetter("base")
    public void setBase(List<String> base) {
        this.base = base;
    }

    /**
     * Converts this Errors1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors1 [" + "base=" + base + "]";
    }

    /**
     * Builds a new {@link Errors1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .base(getBase());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors1}.
     */
    public static class Builder {
        private List<String> base;



        /**
         * Setter for base.
         * @param  base  List of String value for base.
         * @return Builder
         */
        public Builder base(List<String> base) {
            this.base = base;
            return this;
        }

        /**
         * Builds a new {@link Errors1} object using the set fields.
         * @return {@link Errors1}
         */
        public Errors1 build() {
            return new Errors1(base);
        }
    }
}
