/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Errors8 type.
 */
public class Errors8 {
    private List<Member> members;

    /**
     * Default constructor.
     */
    public Errors8() {
    }

    /**
     * Initialization constructor.
     * @param  members  List of Member value for members.
     */
    public Errors8(
            List<Member> members) {
        this.members = members;
    }

    /**
     * Getter for Members.
     * @return Returns the List of Member
     */
    @JsonGetter("members")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Member> getMembers() {
        return members;
    }

    /**
     * Setter for Members.
     * @param members Value for List of Member
     */
    @JsonSetter("members")
    public void setMembers(List<Member> members) {
        this.members = members;
    }

    /**
     * Converts this Errors8 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors8 [" + "members=" + members + "]";
    }

    /**
     * Builds a new {@link Errors8.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors8.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .members(getMembers());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors8}.
     */
    public static class Builder {
        private List<Member> members;



        /**
         * Setter for members.
         * @param  members  List of Member value for members.
         * @return Builder
         */
        public Builder members(List<Member> members) {
            this.members = members;
            return this;
        }

        /**
         * Builds a new {@link Errors8} object using the set fields.
         * @return {@link Errors8}
         */
        public Errors8 build() {
            return new Errors8(members);
        }
    }
}
