/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for InvoiceCustomer type.
 */
public class InvoiceCustomer {
    private Integer chargifyId;
    private String firstName;
    private String lastName;
    private OptionalNullable<String> organization;
    private String email;

    /**
     * Default constructor.
     */
    public InvoiceCustomer() {
    }

    /**
     * Initialization constructor.
     * @param  chargifyId  Integer value for chargifyId.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  organization  String value for organization.
     * @param  email  String value for email.
     */
    public InvoiceCustomer(
            Integer chargifyId,
            String firstName,
            String lastName,
            String organization,
            String email) {
        this.chargifyId = chargifyId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.organization = OptionalNullable.of(organization);
        this.email = email;
    }

    /**
     * Internal initialization constructor.
     */
    protected InvoiceCustomer(Integer chargifyId, String firstName, String lastName,
            OptionalNullable<String> organization, String email) {
        this.chargifyId = chargifyId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.organization = organization;
        this.email = email;
    }

    /**
     * Getter for ChargifyId.
     * @return Returns the Integer
     */
    @JsonGetter("chargify_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getChargifyId() {
        return chargifyId;
    }

    /**
     * Setter for ChargifyId.
     * @param chargifyId Value for Integer
     */
    @JsonSetter("chargify_id")
    public void setChargifyId(Integer chargifyId) {
        this.chargifyId = chargifyId;
    }

    /**
     * Getter for FirstName.
     * @return Returns the String
     */
    @JsonGetter("first_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * @param firstName Value for String
     */
    @JsonSetter("first_name")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for LastName.
     * @return Returns the String
     */
    @JsonGetter("last_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * @param lastName Value for String
     */
    @JsonSetter("last_name")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Internal Getter for Organization.
     * @return Returns the Internal String
     */
    @JsonGetter("organization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetOrganization() {
        return this.organization;
    }

    /**
     * Getter for Organization.
     * @return Returns the String
     */
    public String getOrganization() {
        return OptionalNullable.getFrom(organization);
    }

    /**
     * Setter for Organization.
     * @param organization Value for String
     */
    @JsonSetter("organization")
    public void setOrganization(String organization) {
        this.organization = OptionalNullable.of(organization);
    }

    /**
     * UnSetter for Organization.
     */
    public void unsetOrganization() {
        organization = null;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Converts this InvoiceCustomer into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InvoiceCustomer [" + "chargifyId=" + chargifyId + ", firstName=" + firstName
                + ", lastName=" + lastName + ", organization=" + organization + ", email=" + email
                + "]";
    }

    /**
     * Builds a new {@link InvoiceCustomer.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InvoiceCustomer.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .chargifyId(getChargifyId())
                .firstName(getFirstName())
                .lastName(getLastName())
                .email(getEmail());
        builder.organization = internalGetOrganization();
        return builder;
    }

    /**
     * Class to build instances of {@link InvoiceCustomer}.
     */
    public static class Builder {
        private Integer chargifyId;
        private String firstName;
        private String lastName;
        private OptionalNullable<String> organization;
        private String email;



        /**
         * Setter for chargifyId.
         * @param  chargifyId  Integer value for chargifyId.
         * @return Builder
         */
        public Builder chargifyId(Integer chargifyId) {
            this.chargifyId = chargifyId;
            return this;
        }

        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for organization.
         * @param  organization  String value for organization.
         * @return Builder
         */
        public Builder organization(String organization) {
            this.organization = OptionalNullable.of(organization);
            return this;
        }

        /**
         * UnSetter for organization.
         * @return Builder
         */
        public Builder unsetOrganization() {
            organization = null;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Builds a new {@link InvoiceCustomer} object using the set fields.
         * @return {@link InvoiceCustomer}
         */
        public InvoiceCustomer build() {
            return new InvoiceCustomer(chargifyId, firstName, lastName, organization, email);
        }
    }
}
