/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MetafieldScope type.
 */
public class MetafieldScope {
    private IncludeOptionEnum csv;
    private IncludeOptionEnum invoices;
    private IncludeOptionEnum statements;
    private IncludeOptionEnum portal;
    private IncludeOptionEnum publicShow;
    private IncludeOptionEnum publicEdit;

    /**
     * Default constructor.
     */
    public MetafieldScope() {
    }

    /**
     * Initialization constructor.
     * @param  csv  IncludeOptionEnum value for csv.
     * @param  invoices  IncludeOptionEnum value for invoices.
     * @param  statements  IncludeOptionEnum value for statements.
     * @param  portal  IncludeOptionEnum value for portal.
     * @param  publicShow  IncludeOptionEnum value for publicShow.
     * @param  publicEdit  IncludeOptionEnum value for publicEdit.
     */
    public MetafieldScope(
            IncludeOptionEnum csv,
            IncludeOptionEnum invoices,
            IncludeOptionEnum statements,
            IncludeOptionEnum portal,
            IncludeOptionEnum publicShow,
            IncludeOptionEnum publicEdit) {
        this.csv = csv;
        this.invoices = invoices;
        this.statements = statements;
        this.portal = portal;
        this.publicShow = publicShow;
        this.publicEdit = publicEdit;
    }

    /**
     * Getter for Csv.
     * Include (1) or exclude (0) metafields from the csv export.
     * @return Returns the IncludeOptionEnum
     */
    @JsonGetter("csv")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncludeOptionEnum getCsv() {
        return csv;
    }

    /**
     * Setter for Csv.
     * Include (1) or exclude (0) metafields from the csv export.
     * @param csv Value for IncludeOptionEnum
     */
    @JsonSetter("csv")
    public void setCsv(IncludeOptionEnum csv) {
        this.csv = csv;
    }

    /**
     * Getter for Invoices.
     * Include (1) or exclude (0) metafields from invoices.
     * @return Returns the IncludeOptionEnum
     */
    @JsonGetter("invoices")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncludeOptionEnum getInvoices() {
        return invoices;
    }

    /**
     * Setter for Invoices.
     * Include (1) or exclude (0) metafields from invoices.
     * @param invoices Value for IncludeOptionEnum
     */
    @JsonSetter("invoices")
    public void setInvoices(IncludeOptionEnum invoices) {
        this.invoices = invoices;
    }

    /**
     * Getter for Statements.
     * Include (1) or exclude (0) metafields from statements.
     * @return Returns the IncludeOptionEnum
     */
    @JsonGetter("statements")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncludeOptionEnum getStatements() {
        return statements;
    }

    /**
     * Setter for Statements.
     * Include (1) or exclude (0) metafields from statements.
     * @param statements Value for IncludeOptionEnum
     */
    @JsonSetter("statements")
    public void setStatements(IncludeOptionEnum statements) {
        this.statements = statements;
    }

    /**
     * Getter for Portal.
     * Include (1) or exclude (0) metafields from the portal.
     * @return Returns the IncludeOptionEnum
     */
    @JsonGetter("portal")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncludeOptionEnum getPortal() {
        return portal;
    }

    /**
     * Setter for Portal.
     * Include (1) or exclude (0) metafields from the portal.
     * @param portal Value for IncludeOptionEnum
     */
    @JsonSetter("portal")
    public void setPortal(IncludeOptionEnum portal) {
        this.portal = portal;
    }

    /**
     * Getter for PublicShow.
     * Include (1) or exclude (0) metafields from being viewable by your ecosystem.
     * @return Returns the IncludeOptionEnum
     */
    @JsonGetter("public_show")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncludeOptionEnum getPublicShow() {
        return publicShow;
    }

    /**
     * Setter for PublicShow.
     * Include (1) or exclude (0) metafields from being viewable by your ecosystem.
     * @param publicShow Value for IncludeOptionEnum
     */
    @JsonSetter("public_show")
    public void setPublicShow(IncludeOptionEnum publicShow) {
        this.publicShow = publicShow;
    }

    /**
     * Getter for PublicEdit.
     * Include (1) or exclude (0) metafields from being edited by your ecosystem.
     * @return Returns the IncludeOptionEnum
     */
    @JsonGetter("public_edit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncludeOptionEnum getPublicEdit() {
        return publicEdit;
    }

    /**
     * Setter for PublicEdit.
     * Include (1) or exclude (0) metafields from being edited by your ecosystem.
     * @param publicEdit Value for IncludeOptionEnum
     */
    @JsonSetter("public_edit")
    public void setPublicEdit(IncludeOptionEnum publicEdit) {
        this.publicEdit = publicEdit;
    }

    /**
     * Converts this MetafieldScope into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MetafieldScope [" + "csv=" + csv + ", invoices=" + invoices + ", statements="
                + statements + ", portal=" + portal + ", publicShow=" + publicShow + ", publicEdit="
                + publicEdit + "]";
    }

    /**
     * Builds a new {@link MetafieldScope.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MetafieldScope.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .csv(getCsv())
                .invoices(getInvoices())
                .statements(getStatements())
                .portal(getPortal())
                .publicShow(getPublicShow())
                .publicEdit(getPublicEdit());
        return builder;
    }

    /**
     * Class to build instances of {@link MetafieldScope}.
     */
    public static class Builder {
        private IncludeOptionEnum csv;
        private IncludeOptionEnum invoices;
        private IncludeOptionEnum statements;
        private IncludeOptionEnum portal;
        private IncludeOptionEnum publicShow;
        private IncludeOptionEnum publicEdit;



        /**
         * Setter for csv.
         * @param  csv  IncludeOptionEnum value for csv.
         * @return Builder
         */
        public Builder csv(IncludeOptionEnum csv) {
            this.csv = csv;
            return this;
        }

        /**
         * Setter for invoices.
         * @param  invoices  IncludeOptionEnum value for invoices.
         * @return Builder
         */
        public Builder invoices(IncludeOptionEnum invoices) {
            this.invoices = invoices;
            return this;
        }

        /**
         * Setter for statements.
         * @param  statements  IncludeOptionEnum value for statements.
         * @return Builder
         */
        public Builder statements(IncludeOptionEnum statements) {
            this.statements = statements;
            return this;
        }

        /**
         * Setter for portal.
         * @param  portal  IncludeOptionEnum value for portal.
         * @return Builder
         */
        public Builder portal(IncludeOptionEnum portal) {
            this.portal = portal;
            return this;
        }

        /**
         * Setter for publicShow.
         * @param  publicShow  IncludeOptionEnum value for publicShow.
         * @return Builder
         */
        public Builder publicShow(IncludeOptionEnum publicShow) {
            this.publicShow = publicShow;
            return this;
        }

        /**
         * Setter for publicEdit.
         * @param  publicEdit  IncludeOptionEnum value for publicEdit.
         * @return Builder
         */
        public Builder publicEdit(IncludeOptionEnum publicEdit) {
            this.publicEdit = publicEdit;
            return this;
        }

        /**
         * Builds a new {@link MetafieldScope} object using the set fields.
         * @return {@link MetafieldScope}
         */
        public MetafieldScope build() {
            return new MetafieldScope(csv, invoices, statements, portal, publicShow, publicEdit);
        }
    }
}
