/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MRRMovement type.
 */
public class MRRMovement {
    private Integer amount;
    private String category;

    /**
     * Default constructor.
     */
    public MRRMovement() {
    }

    /**
     * Initialization constructor.
     * @param  amount  Integer value for amount.
     * @param  category  String value for category.
     */
    public MRRMovement(
            Integer amount,
            String category) {
        this.amount = amount;
        this.category = category;
    }

    /**
     * Getter for Amount.
     * @return Returns the Integer
     */
    @JsonGetter("amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for Integer
     */
    @JsonSetter("amount")
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * Getter for Category.
     * @return Returns the String
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * @param category Value for String
     */
    @JsonSetter("category")
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Converts this MRRMovement into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MRRMovement [" + "amount=" + amount + ", category=" + category + "]";
    }

    /**
     * Builds a new {@link MRRMovement.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MRRMovement.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .amount(getAmount())
                .category(getCategory());
        return builder;
    }

    /**
     * Class to build instances of {@link MRRMovement}.
     */
    public static class Builder {
        private Integer amount;
        private String category;



        /**
         * Setter for amount.
         * @param  amount  Integer value for amount.
         * @return Builder
         */
        public Builder amount(Integer amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  String value for category.
         * @return Builder
         */
        public Builder category(String category) {
            this.category = category;
            return this;
        }

        /**
         * Builds a new {@link MRRMovement} object using the set fields.
         * @return {@link MRRMovement}
         */
        public MRRMovement build() {
            return new MRRMovement(amount, category);
        }
    }
}
