/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for ProformaInvoiceLineItem type.
 */
public class ProformaInvoiceLineItem {
    private String uid;
    private String title;
    private String description;
    private String quantity;
    private String unitPrice;
    private String subtotalAmount;
    private String discountAmount;
    private String taxAmount;
    private String totalAmount;
    private Boolean tieredUnitPrice;
    private String periodRangeStart;
    private String periodRangeEnd;
    private Integer productId;
    private Integer productVersion;
    private Integer productPricePointId;
    private OptionalNullable<String> componentId;
    private OptionalNullable<String> pricePointId;

    /**
     * Default constructor.
     */
    public ProformaInvoiceLineItem() {
    }

    /**
     * Initialization constructor.
     * @param  uid  String value for uid.
     * @param  title  String value for title.
     * @param  description  String value for description.
     * @param  quantity  String value for quantity.
     * @param  unitPrice  String value for unitPrice.
     * @param  subtotalAmount  String value for subtotalAmount.
     * @param  discountAmount  String value for discountAmount.
     * @param  taxAmount  String value for taxAmount.
     * @param  totalAmount  String value for totalAmount.
     * @param  tieredUnitPrice  Boolean value for tieredUnitPrice.
     * @param  periodRangeStart  String value for periodRangeStart.
     * @param  periodRangeEnd  String value for periodRangeEnd.
     * @param  productId  Integer value for productId.
     * @param  productVersion  Integer value for productVersion.
     * @param  productPricePointId  Integer value for productPricePointId.
     * @param  componentId  String value for componentId.
     * @param  pricePointId  String value for pricePointId.
     */
    public ProformaInvoiceLineItem(
            String uid,
            String title,
            String description,
            String quantity,
            String unitPrice,
            String subtotalAmount,
            String discountAmount,
            String taxAmount,
            String totalAmount,
            Boolean tieredUnitPrice,
            String periodRangeStart,
            String periodRangeEnd,
            Integer productId,
            Integer productVersion,
            Integer productPricePointId,
            String componentId,
            String pricePointId) {
        this.uid = uid;
        this.title = title;
        this.description = description;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.subtotalAmount = subtotalAmount;
        this.discountAmount = discountAmount;
        this.taxAmount = taxAmount;
        this.totalAmount = totalAmount;
        this.tieredUnitPrice = tieredUnitPrice;
        this.periodRangeStart = periodRangeStart;
        this.periodRangeEnd = periodRangeEnd;
        this.productId = productId;
        this.productVersion = productVersion;
        this.productPricePointId = productPricePointId;
        this.componentId = OptionalNullable.of(componentId);
        this.pricePointId = OptionalNullable.of(pricePointId);
    }

    /**
     * Internal initialization constructor.
     */
    protected ProformaInvoiceLineItem(String uid, String title, String description, String quantity,
            String unitPrice, String subtotalAmount, String discountAmount, String taxAmount,
            String totalAmount, Boolean tieredUnitPrice, String periodRangeStart,
            String periodRangeEnd, Integer productId, Integer productVersion,
            Integer productPricePointId, OptionalNullable<String> componentId,
            OptionalNullable<String> pricePointId) {
        this.uid = uid;
        this.title = title;
        this.description = description;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.subtotalAmount = subtotalAmount;
        this.discountAmount = discountAmount;
        this.taxAmount = taxAmount;
        this.totalAmount = totalAmount;
        this.tieredUnitPrice = tieredUnitPrice;
        this.periodRangeStart = periodRangeStart;
        this.periodRangeEnd = periodRangeEnd;
        this.productId = productId;
        this.productVersion = productVersion;
        this.productPricePointId = productPricePointId;
        this.componentId = componentId;
        this.pricePointId = pricePointId;
    }

    /**
     * Getter for Uid.
     * @return Returns the String
     */
    @JsonGetter("uid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUid() {
        return uid;
    }

    /**
     * Setter for Uid.
     * @param uid Value for String
     */
    @JsonSetter("uid")
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Quantity.
     * @return Returns the String
     */
    @JsonGetter("quantity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getQuantity() {
        return quantity;
    }

    /**
     * Setter for Quantity.
     * @param quantity Value for String
     */
    @JsonSetter("quantity")
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for UnitPrice.
     * @return Returns the String
     */
    @JsonGetter("unit_price")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Setter for UnitPrice.
     * @param unitPrice Value for String
     */
    @JsonSetter("unit_price")
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * Getter for SubtotalAmount.
     * @return Returns the String
     */
    @JsonGetter("subtotal_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSubtotalAmount() {
        return subtotalAmount;
    }

    /**
     * Setter for SubtotalAmount.
     * @param subtotalAmount Value for String
     */
    @JsonSetter("subtotal_amount")
    public void setSubtotalAmount(String subtotalAmount) {
        this.subtotalAmount = subtotalAmount;
    }

    /**
     * Getter for DiscountAmount.
     * @return Returns the String
     */
    @JsonGetter("discount_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDiscountAmount() {
        return discountAmount;
    }

    /**
     * Setter for DiscountAmount.
     * @param discountAmount Value for String
     */
    @JsonSetter("discount_amount")
    public void setDiscountAmount(String discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * Getter for TaxAmount.
     * @return Returns the String
     */
    @JsonGetter("tax_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTaxAmount() {
        return taxAmount;
    }

    /**
     * Setter for TaxAmount.
     * @param taxAmount Value for String
     */
    @JsonSetter("tax_amount")
    public void setTaxAmount(String taxAmount) {
        this.taxAmount = taxAmount;
    }

    /**
     * Getter for TotalAmount.
     * @return Returns the String
     */
    @JsonGetter("total_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * @param totalAmount Value for String
     */
    @JsonSetter("total_amount")
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for TieredUnitPrice.
     * @return Returns the Boolean
     */
    @JsonGetter("tiered_unit_price")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getTieredUnitPrice() {
        return tieredUnitPrice;
    }

    /**
     * Setter for TieredUnitPrice.
     * @param tieredUnitPrice Value for Boolean
     */
    @JsonSetter("tiered_unit_price")
    public void setTieredUnitPrice(Boolean tieredUnitPrice) {
        this.tieredUnitPrice = tieredUnitPrice;
    }

    /**
     * Getter for PeriodRangeStart.
     * @return Returns the String
     */
    @JsonGetter("period_range_start")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPeriodRangeStart() {
        return periodRangeStart;
    }

    /**
     * Setter for PeriodRangeStart.
     * @param periodRangeStart Value for String
     */
    @JsonSetter("period_range_start")
    public void setPeriodRangeStart(String periodRangeStart) {
        this.periodRangeStart = periodRangeStart;
    }

    /**
     * Getter for PeriodRangeEnd.
     * @return Returns the String
     */
    @JsonGetter("period_range_end")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPeriodRangeEnd() {
        return periodRangeEnd;
    }

    /**
     * Setter for PeriodRangeEnd.
     * @param periodRangeEnd Value for String
     */
    @JsonSetter("period_range_end")
    public void setPeriodRangeEnd(String periodRangeEnd) {
        this.periodRangeEnd = periodRangeEnd;
    }

    /**
     * Getter for ProductId.
     * @return Returns the Integer
     */
    @JsonGetter("product_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getProductId() {
        return productId;
    }

    /**
     * Setter for ProductId.
     * @param productId Value for Integer
     */
    @JsonSetter("product_id")
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * Getter for ProductVersion.
     * @return Returns the Integer
     */
    @JsonGetter("product_version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getProductVersion() {
        return productVersion;
    }

    /**
     * Setter for ProductVersion.
     * @param productVersion Value for Integer
     */
    @JsonSetter("product_version")
    public void setProductVersion(Integer productVersion) {
        this.productVersion = productVersion;
    }

    /**
     * Getter for ProductPricePointId.
     * @return Returns the Integer
     */
    @JsonGetter("product_price_point_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getProductPricePointId() {
        return productPricePointId;
    }

    /**
     * Setter for ProductPricePointId.
     * @param productPricePointId Value for Integer
     */
    @JsonSetter("product_price_point_id")
    public void setProductPricePointId(Integer productPricePointId) {
        this.productPricePointId = productPricePointId;
    }

    /**
     * Internal Getter for ComponentId.
     * @return Returns the Internal String
     */
    @JsonGetter("component_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetComponentId() {
        return this.componentId;
    }

    /**
     * Getter for ComponentId.
     * @return Returns the String
     */
    public String getComponentId() {
        return OptionalNullable.getFrom(componentId);
    }

    /**
     * Setter for ComponentId.
     * @param componentId Value for String
     */
    @JsonSetter("component_id")
    public void setComponentId(String componentId) {
        this.componentId = OptionalNullable.of(componentId);
    }

    /**
     * UnSetter for ComponentId.
     */
    public void unsetComponentId() {
        componentId = null;
    }

    /**
     * Internal Getter for PricePointId.
     * @return Returns the Internal String
     */
    @JsonGetter("price_point_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetPricePointId() {
        return this.pricePointId;
    }

    /**
     * Getter for PricePointId.
     * @return Returns the String
     */
    public String getPricePointId() {
        return OptionalNullable.getFrom(pricePointId);
    }

    /**
     * Setter for PricePointId.
     * @param pricePointId Value for String
     */
    @JsonSetter("price_point_id")
    public void setPricePointId(String pricePointId) {
        this.pricePointId = OptionalNullable.of(pricePointId);
    }

    /**
     * UnSetter for PricePointId.
     */
    public void unsetPricePointId() {
        pricePointId = null;
    }

    /**
     * Converts this ProformaInvoiceLineItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProformaInvoiceLineItem [" + "uid=" + uid + ", title=" + title + ", description="
                + description + ", quantity=" + quantity + ", unitPrice=" + unitPrice
                + ", subtotalAmount=" + subtotalAmount + ", discountAmount=" + discountAmount
                + ", taxAmount=" + taxAmount + ", totalAmount=" + totalAmount + ", tieredUnitPrice="
                + tieredUnitPrice + ", periodRangeStart=" + periodRangeStart + ", periodRangeEnd="
                + periodRangeEnd + ", productId=" + productId + ", productVersion=" + productVersion
                + ", productPricePointId=" + productPricePointId + ", componentId=" + componentId
                + ", pricePointId=" + pricePointId + "]";
    }

    /**
     * Builds a new {@link ProformaInvoiceLineItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProformaInvoiceLineItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .uid(getUid())
                .title(getTitle())
                .description(getDescription())
                .quantity(getQuantity())
                .unitPrice(getUnitPrice())
                .subtotalAmount(getSubtotalAmount())
                .discountAmount(getDiscountAmount())
                .taxAmount(getTaxAmount())
                .totalAmount(getTotalAmount())
                .tieredUnitPrice(getTieredUnitPrice())
                .periodRangeStart(getPeriodRangeStart())
                .periodRangeEnd(getPeriodRangeEnd())
                .productId(getProductId())
                .productVersion(getProductVersion())
                .productPricePointId(getProductPricePointId());
        builder.componentId = internalGetComponentId();
        builder.pricePointId = internalGetPricePointId();
        return builder;
    }

    /**
     * Class to build instances of {@link ProformaInvoiceLineItem}.
     */
    public static class Builder {
        private String uid;
        private String title;
        private String description;
        private String quantity;
        private String unitPrice;
        private String subtotalAmount;
        private String discountAmount;
        private String taxAmount;
        private String totalAmount;
        private Boolean tieredUnitPrice;
        private String periodRangeStart;
        private String periodRangeEnd;
        private Integer productId;
        private Integer productVersion;
        private Integer productPricePointId;
        private OptionalNullable<String> componentId;
        private OptionalNullable<String> pricePointId;



        /**
         * Setter for uid.
         * @param  uid  String value for uid.
         * @return Builder
         */
        public Builder uid(String uid) {
            this.uid = uid;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for quantity.
         * @param  quantity  String value for quantity.
         * @return Builder
         */
        public Builder quantity(String quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * Setter for unitPrice.
         * @param  unitPrice  String value for unitPrice.
         * @return Builder
         */
        public Builder unitPrice(String unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        /**
         * Setter for subtotalAmount.
         * @param  subtotalAmount  String value for subtotalAmount.
         * @return Builder
         */
        public Builder subtotalAmount(String subtotalAmount) {
            this.subtotalAmount = subtotalAmount;
            return this;
        }

        /**
         * Setter for discountAmount.
         * @param  discountAmount  String value for discountAmount.
         * @return Builder
         */
        public Builder discountAmount(String discountAmount) {
            this.discountAmount = discountAmount;
            return this;
        }

        /**
         * Setter for taxAmount.
         * @param  taxAmount  String value for taxAmount.
         * @return Builder
         */
        public Builder taxAmount(String taxAmount) {
            this.taxAmount = taxAmount;
            return this;
        }

        /**
         * Setter for totalAmount.
         * @param  totalAmount  String value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(String totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for tieredUnitPrice.
         * @param  tieredUnitPrice  Boolean value for tieredUnitPrice.
         * @return Builder
         */
        public Builder tieredUnitPrice(Boolean tieredUnitPrice) {
            this.tieredUnitPrice = tieredUnitPrice;
            return this;
        }

        /**
         * Setter for periodRangeStart.
         * @param  periodRangeStart  String value for periodRangeStart.
         * @return Builder
         */
        public Builder periodRangeStart(String periodRangeStart) {
            this.periodRangeStart = periodRangeStart;
            return this;
        }

        /**
         * Setter for periodRangeEnd.
         * @param  periodRangeEnd  String value for periodRangeEnd.
         * @return Builder
         */
        public Builder periodRangeEnd(String periodRangeEnd) {
            this.periodRangeEnd = periodRangeEnd;
            return this;
        }

        /**
         * Setter for productId.
         * @param  productId  Integer value for productId.
         * @return Builder
         */
        public Builder productId(Integer productId) {
            this.productId = productId;
            return this;
        }

        /**
         * Setter for productVersion.
         * @param  productVersion  Integer value for productVersion.
         * @return Builder
         */
        public Builder productVersion(Integer productVersion) {
            this.productVersion = productVersion;
            return this;
        }

        /**
         * Setter for productPricePointId.
         * @param  productPricePointId  Integer value for productPricePointId.
         * @return Builder
         */
        public Builder productPricePointId(Integer productPricePointId) {
            this.productPricePointId = productPricePointId;
            return this;
        }

        /**
         * Setter for componentId.
         * @param  componentId  String value for componentId.
         * @return Builder
         */
        public Builder componentId(String componentId) {
            this.componentId = OptionalNullable.of(componentId);
            return this;
        }

        /**
         * UnSetter for componentId.
         * @return Builder
         */
        public Builder unsetComponentId() {
            componentId = null;
            return this;
        }

        /**
         * Setter for pricePointId.
         * @param  pricePointId  String value for pricePointId.
         * @return Builder
         */
        public Builder pricePointId(String pricePointId) {
            this.pricePointId = OptionalNullable.of(pricePointId);
            return this;
        }

        /**
         * UnSetter for pricePointId.
         * @return Builder
         */
        public Builder unsetPricePointId() {
            pricePointId = null;
            return this;
        }

        /**
         * Builds a new {@link ProformaInvoiceLineItem} object using the set fields.
         * @return {@link ProformaInvoiceLineItem}
         */
        public ProformaInvoiceLineItem build() {
            return new ProformaInvoiceLineItem(uid, title, description, quantity, unitPrice,
                    subtotalAmount, discountAmount, taxAmount, totalAmount, tieredUnitPrice,
                    periodRangeStart, periodRangeEnd, productId, productVersion,
                    productPricePointId, componentId, pricePointId);
        }
    }
}
