/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * RecurringSchemeEnum to be used.
 */
public enum RecurringSchemeEnum {
    DO_NOT_RECUR,

    RECUR_INDEFINITELY;


    private static TreeMap<String, RecurringSchemeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        DO_NOT_RECUR.value = "do_not_recur";
        RECUR_INDEFINITELY.value = "recur_indefinitely";

        valueMap.put("do_not_recur", DO_NOT_RECUR);
        valueMap.put("recur_indefinitely", RECUR_INDEFINITELY);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static RecurringSchemeEnum constructFromString(String toConvert) throws IOException {
        RecurringSchemeEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static RecurringSchemeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of RecurringSchemeEnum values to list of string values.
     * @param toConvert The list of RecurringSchemeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<RecurringSchemeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (RecurringSchemeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 