/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SubscriptionsPrepaymentsJsonResponse type.
 */
public class SubscriptionsPrepaymentsJsonResponse {
    private List<PrepaymentResponse> prepayments;

    /**
     * Default constructor.
     */
    public SubscriptionsPrepaymentsJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  prepayments  List of PrepaymentResponse value for prepayments.
     */
    public SubscriptionsPrepaymentsJsonResponse(
            List<PrepaymentResponse> prepayments) {
        this.prepayments = prepayments;
    }

    /**
     * Getter for Prepayments.
     * @return Returns the List of PrepaymentResponse
     */
    @JsonGetter("prepayments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PrepaymentResponse> getPrepayments() {
        return prepayments;
    }

    /**
     * Setter for Prepayments.
     * @param prepayments Value for List of PrepaymentResponse
     */
    @JsonSetter("prepayments")
    public void setPrepayments(List<PrepaymentResponse> prepayments) {
        this.prepayments = prepayments;
    }

    /**
     * Converts this SubscriptionsPrepaymentsJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SubscriptionsPrepaymentsJsonResponse [" + "prepayments=" + prepayments + "]";
    }

    /**
     * Builds a new {@link SubscriptionsPrepaymentsJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SubscriptionsPrepaymentsJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .prepayments(getPrepayments());
        return builder;
    }

    /**
     * Class to build instances of {@link SubscriptionsPrepaymentsJsonResponse}.
     */
    public static class Builder {
        private List<PrepaymentResponse> prepayments;



        /**
         * Setter for prepayments.
         * @param  prepayments  List of PrepaymentResponse value for prepayments.
         * @return Builder
         */
        public Builder prepayments(List<PrepaymentResponse> prepayments) {
            this.prepayments = prepayments;
            return this;
        }

        /**
         * Builds a new {@link SubscriptionsPrepaymentsJsonResponse} object using the set fields.
         * @return {@link SubscriptionsPrepaymentsJsonResponse}
         */
        public SubscriptionsPrepaymentsJsonResponse build() {
            return new SubscriptionsPrepaymentsJsonResponse(prepayments);
        }
    }
}
