/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * WebhookOrderEnum to be used.
 */
public enum WebhookOrderEnum {
    NEWEST_FIRST,

    OLDEST_FIRST;


    private static TreeMap<String, WebhookOrderEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        NEWEST_FIRST.value = "newest_first";
        OLDEST_FIRST.value = "oldest_first";

        valueMap.put("newest_first", NEWEST_FIRST);
        valueMap.put("oldest_first", OLDEST_FIRST);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static WebhookOrderEnum constructFromString(String toConvert) throws IOException {
        WebhookOrderEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static WebhookOrderEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of WebhookOrderEnum values to list of string values.
     * @param toConvert The list of WebhookOrderEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<WebhookOrderEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (WebhookOrderEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 