/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.exceptions;

import com.chargify.subdomain.models.Errors12;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for ComponentsPricePointsSegmentsBulkJson422ErrorException type.
 */
public class ComponentsPricePointsSegmentsBulkJson422ErrorException extends ApiException {
    private static final long serialVersionUID = 133691009819619399L;
    private Errors12 errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public ComponentsPricePointsSegmentsBulkJson422ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Errors.
     * @return Returns the Errors12
     */
    @JsonGetter("errors")
    public Errors12 getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for Errors12
     */
    @JsonSetter("errors")
    private void setErrors(Errors12 errors) {
        this.errors = errors;
    }
}
