/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.exceptions;

import com.chargify.subdomain.models.Errors;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for PortalCustomersManagementLinkJson429ErrorException type.
 */
public class PortalCustomersManagementLinkJson429ErrorException extends ApiException {
    private static final long serialVersionUID = 79199901003402817L;
    private Errors errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public PortalCustomersManagementLinkJson429ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Errors.
     * @return Returns the Errors
     */
    @JsonGetter("errors")
    public Errors getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for Errors
     */
    @JsonSetter("errors")
    private void setErrors(Errors errors) {
        this.errors = errors;
    }
}
