/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.exceptions;

import com.chargify.subdomain.models.Errors2;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;
import java.util.List;

/**
 * This is a model class for SubscriptionsPricePointsJson422ErrorException type.
 */
public class SubscriptionsPricePointsJson422ErrorException extends ApiException {
    private static final long serialVersionUID = -73303146101769628L;
    private List<Errors2> errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public SubscriptionsPricePointsJson422ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Errors.
     * @return Returns the List of Errors2
     */
    @JsonGetter("errors")
    public List<Errors2> getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for List of Errors2
     */
    @JsonSetter("errors")
    private void setErrors(List<Errors2> errors) {
        this.errors = errors;
    }
}
