/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.exceptions;

import com.chargify.subdomain.models.Errors7;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for SubscriptionGroupsSignupJson422ErrorException type.
 */
public class SubscriptionGroupsSignupJson422ErrorException extends ApiException {
    private static final long serialVersionUID = -119380836288668554L;
    private Errors7 errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public SubscriptionGroupsSignupJson422ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Errors.
     * @return Returns the Errors7
     */
    @JsonGetter("errors")
    public Errors7 getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for Errors7
     */
    @JsonSetter("errors")
    private void setErrors(Errors7 errors) {
        this.errors = errors;
    }
}
