/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.exceptions;

import com.chargify.subdomain.models.Errors18;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for SubscriptionsProformaInvoicesPreviewJson400ErrorException type.
 */
public class SubscriptionsProformaInvoicesPreviewJson400ErrorException extends ApiException {
    private static final long serialVersionUID = 32213822852819861L;
    private Errors18 errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public SubscriptionsProformaInvoicesPreviewJson400ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Errors.
     * @return Returns the Errors18
     */
    @JsonGetter("errors")
    public Errors18 getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for Errors18
     */
    @JsonSetter("errors")
    private void setErrors(Errors18 errors) {
        this.errors = errors;
    }
}
