/*
 * MaxioAdvancedBillingFormerlyChargifyAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.chargify.subdomain.models.containers;

import com.chargify.subdomain.ApiHelper;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = CreateOrUpdateCouponRestrictedProducts.CreateOrUpdateCouponRestrictedProductsDeserializer.class)
public abstract class CreateOrUpdateCouponRestrictedProducts {
    
    /**
     * This is Map of Boolean case.
     * @param mapOfBoolean Map of String, value for mapOfBoolean.
     * @return The MapOfBooleanCase object.
     */
    public static CreateOrUpdateCouponRestrictedProducts fromMapOfBoolean(
            Map<String, Boolean> mapOfBoolean) {
        return mapOfBoolean == null ? null : new MapOfBooleanCase(mapOfBoolean);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R mapOfBoolean(Map<String, Boolean> mapOfBoolean);
    }

    /**
     * This is a implementation class for MapOfBooleanCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "Map<String, Boolean>")
    private static class MapOfBooleanCase extends CreateOrUpdateCouponRestrictedProducts {

        @JsonValue
        private Map<String, Boolean> mapOfBoolean;

        MapOfBooleanCase(Map<String, Boolean> mapOfBoolean) {
            this.mapOfBoolean = mapOfBoolean;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.mapOfBoolean(this.mapOfBoolean);
        }

        @JsonCreator
        private MapOfBooleanCase(JsonNode jsonNode) throws IOException {
            this.mapOfBoolean = ApiHelper.deserialize(jsonNode,
                new TypeReference<Map<String, Boolean>>(){});
        }

        @Override
        public String toString() {
            return mapOfBoolean.toString();
        }
    }

    /**
     * This is a custom deserializer class for CreateOrUpdateCouponRestrictedProducts.
     */
    protected static class CreateOrUpdateCouponRestrictedProductsDeserializer
            extends JsonDeserializer<CreateOrUpdateCouponRestrictedProducts> {

        @Override
        public CreateOrUpdateCouponRestrictedProducts deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(MapOfBooleanCase.class), true);
        }
    }

}
