name: Build & run E2E tests
on:
  push:
    branches:
      - "tests"
  pull_request:
    branches:
      - "tests"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
      - name: Run tests
        id: build
        shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DOMAIN: ${{ secrets.DOMAIN }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
            mvn install
            cd tests
            mvn --batch-mode --update-snapshots verify --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
