name: Build & run E2E tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
      - name: Run tests
        id: build
        shell: bash
        env:
          SUBDOMAINS: ${{ secrets.SUBDOMAINS }}
          API_KEYS: ${{ secrets.API_KEYS }}
          SITE_ID: ${{ secrets.SITE_ID }}
          PRECONFIGURED_SUBDOMAIN: ${{ secrets.PRECONFIGURED_SUBDOMAIN }}
          PRECONFIGURED_API_KEY: ${{ secrets.PRECONFIGURED_API_KEY }}
        run: |
            mvn install
            cd tests
            mvn --batch-mode --update-snapshots verify --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
