name: Create Jira Task Template

on:
  workflow_call:
    inputs:
      sdk-name:
        required: true
        type: string

jobs:
  create-jira-task:
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: "${{ github.event.issue.title }}"
      ISSUE_BODY: "${{ github.event.issue.body }}"
      ISSUE_URL: "${{ github.event.issue.html_url }}"
      ISSUE_USER: "${{ github.event.issue.user.login }}"
    steps:
      - name: Create Jira Task
        run: |
          JIRA_PAYLOAD=$(jq -n \
            --arg project_key "DE" \
            --arg jira_epic_key "DE-1012" \
            --arg summary "[${{ inputs.sdk-name }}] ${ISSUE_TITLE}" \
            --arg description "GitHub issue created by ${ISSUE_USER}:
          
            ${ISSUE_BODY}
          
            Link: ${ISSUE_URL}" \
            '{
              fields: {
                project: { key: $project_key },
                summary: $summary,
                description: $description,
                issuetype: { name: "Defect" },
                labels: ["github_issue"],
                components: [ { name: "SDK" } ],
                parent: { key: $jira_epic_key }
              }
            }')

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Content-Type: application/json" \
          --user "${{ secrets.ATLASSIAN_TOKEN }}" "${{ secrets.ATLASSIAN_URL }}/rest/api/2/issue" \
          --data "${JIRA_PAYLOAD}")

           if [ "$RESPONSE" -ne 201 ]; then
            echo "Error: Failed to create Jira issue. HTTP response code: $RESPONSE"
            echo "Response Body: $(jq . response.json)"
            exit 1
          else
            echo "Jira issue created successfully!"
          fi
